title:             学无止境
email:             1258061993@qq.com
description:       关于技术、读书、学习
author:            猎手之远殇
baseurl:           ""
url:               "http://sh-learn.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   sh-learn
#facebook_username: StartBootstrap
zhihu_username: sh-learn
weibo_username: 6854461296

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
